{% set version = '1.0-9' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-th.data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TH.data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TH.data/TH.data_{{ version }}.tar.gz
  sha256: d8318a172ce2b9f7f284dc297c8a8d5093de8eccbb566c8e7580e70938dfae0f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: dplyr, gdata, plyr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-survival

  run:
    - r-base
    - r-mass
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('TH.data')"           # [not win]
    - "\"%R%\" -e \"library('TH.data')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=TH.data
  license: GPL-3
  summary: Contains data sets used in other packages Torsten Hothorn maintains.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: TH.data
# Title: TH's Data Archive
# Date: 2018-07-04
# Version: 1.0-9
# Authors@R: c(person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org"))
# Description: Contains data sets used in other packages Torsten Hothorn maintains.
# Depends: R (>= 2.10.0), survival, MASS
# Suggests: dplyr, gdata, plyr
# LazyData: yes
# License: GPL-3
# NeedsCompilation: no
# Packaged: 2018-07-04 11:14:12 UTC; hothorn
# Author: Torsten Hothorn [aut, cre]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-07-10 16:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
