travis:
  secure:
    BINSTAR_TOKEN: ETeAUNtlarXNaHJ8dnEBMei4C25sD95ELU6wKE2ZKvn6upkp1Sg8XtYxygUf1v1BchhmExlOheeZZ7QA0pWbMLJhEbQId2XEwyKbr7PO5JU8FKBpRnEN6YeLPZihW1ZKasY1ObPiPK7zsm0gboTlQWUPTOJD7CSMOSyzktYDVfluxOYT7hVz7UXTd+TPXQxmAoxR8kSEHEbhSq9K0zVU5RU+BV+ROxq2rn6E9Dp8UgLymdoRMXrCdVxtNoQOQcIHFTTCl2309PcdDxhDSxtpk8zFOjfH0/fKcbfh1Gq7ZIsc2KMn93TbqOoRgg7zJ+fE9kU0Q7GIWaX7h9EIXEW2a5VPJj9ssxpotLDQ/u235O0+u4wlQxaKGPqrwipBKr27ZRZxnYxIEDDV+25UDBGNmR6svGN0yMcMBZSrxwy3Ty84zXTN03n1qbfPnCyAw00mV6mGGQOEC9lkKtb10vyYKdvhm81i4jd2H5NX28cNvAKc9IqDHLgmWtl/cTJ3BYbZaRSxVCVVMIIoz7JH6rQkfqPVP2+q2u3Cba3yxgGKUEFgJt2e2JTTd8jBowaOMx/CAd5iMF2cwEqnOTl3/tdaI73l4ac7atPc6mTLlfNzKJYQUWV8RF++kRM+MnZtvrORggb20CUJ3z/OhlUQ0Cv+p9//dJa+4cQAoUA9unI6p+k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
