travis:
  secure:
    BINSTAR_TOKEN: RvRc/sCrEej5Q3z4NlgQxQJhHX2oeUCPh3NMdB9No5FU+ohAwyxL/zSs+xTK5Bv8BKDcg+r+kPsPtPGgdGyQAT4iJ79dE4ioAvX/EeKU7ei3oVI4qY5DuE995xMa2JTxXcjj8MOvRR2OJzeTm98kAnfzhBkA53miOtw5iW4lfh8l5gSwOpLq+CHYzdZH5q/edFiLOI9d4BO1+P1o5d/kVHMMgYNK/WfaNc2Q/Q/3PzoniiM1Xxd4NtEYHRG2ElCZNMI9Um87l7czlYAPqWnteurpSdo2nhh64Ke9mYzFrD7GhS5ANRnBKGsbWC95EoTa9mtriPQhb9H+o294DevXL0i3l/6zycrnqfrtYk4/fBy6tNBDeKVGC9Y0L1Jy84pJ4B5uG7EqriY+ri9QRijcPALkbHd5dieFxi31MoJUjBFC6XJtMqblhwphuJSjqux4nqh5KYsjcG2nXVBK6w9cCxh40LmjJR1Cr3SK8QnHfbaB79lXhvSAQoiD8+NUiw5u6KjEMXJsvNjRYVA5ElMKDiZ9PSRoL+mS5hRRCrL/B3fFXNdNRlHheyQw0KS4pesH+vHaUtEDUqnnC3Lpem567AL1vnSbSZNZDjyPuaRn/axdjm9ya9qlCE/+UzF3s4wIfAvDlhyq5mGhTS9tBiOIiX7P7sPhH9Y+X5K1PRk5o68=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
